import NavBar from '@/components/NavBar/NavBar';
import './globals.scss';
import { ReactNode } from 'react';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: ReactNode;
};

export default function RootLayout(props: RootLayoutProps) {
	console.log(props);
	return (
		<html lang="en">
			<body>
				<NavBar client-only />
				<main className="p-2">{props.children}</main>
				<div id="portal-root"></div>
			</body>
		</html>
	);
}
